"""agregar_refresh_token_a_usuarios

Revision ID: 72a5ca48158b
Revises: 1fcb98e5fe26
Create Date: 2026-09-24 09:50:24.407846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a5ca48158b'
down_revision: Union[str, None] = '1fcb98e5fe26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('refreshToken', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'refreshToken')
    # ### end Alembic commands ###
