"""crear_tablas_conocimiento_reclamos_comentarios_historial

Revision ID: df44491c5c14
Revises: 72a5ca48158b
Create Date: 2026-09-24 13:24:30.656173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df44491c5c14'
down_revision: Union[str, None] = '72a5ca48158b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_table('articulosConocimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('resumen', sa.String(length=500), nullable=True),
    sa.Column('contenidoTecnico', sa.Text(), nullable=False),
    sa.Column('etiquetas', sa.String(length=255), nullable=False),
    sa.Column('vecesUtilizado', sa.Integer(), nullable=False),
    sa.Column('categoriaId', sa.Integer(), nullable=False),
    sa.Column('autorId', sa.Integer(), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autorId'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['categoriaId'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articulos_relacionados',
    sa.Column('articulo_origen_id', sa.Integer(), nullable=False),
    sa.Column('articulo_destino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_destino_id'], ['articulosConocimiento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['articulo_origen_id'], ['articulosConocimiento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('articulo_origen_id', 'articulo_destino_id')
    )
    op.create_table('plantillasRespuesta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('articuloId', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('contenidoUsuario', sa.Text(), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['articuloId'], ['articulosConocimiento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reclamos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioridad_reclamo_enum'), nullable=False),
    sa.Column('estado', sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING_INFO', 'RESOLVED', 'CLOSED', 'CANCELLED', name='estado_reclamo_enum'), nullable=False),
    sa.Column('categoriaId', sa.Integer(), nullable=False),
    sa.Column('creadorId', sa.Integer(), nullable=False),
    sa.Column('responsableId', sa.Integer(), nullable=True),
    sa.Column('articuloAplicadoId', sa.Integer(), nullable=True),
    sa.Column('plantillaAplicadaId', sa.Integer(), nullable=True),
    sa.Column('porcentajeCoincidenciaAuto', sa.Float(), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechaResolucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fechaCierre', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['articuloAplicadoId'], ['articulosConocimiento.id'], ),
    sa.ForeignKeyConstraint(['categoriaId'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['creadorId'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['plantillaAplicadaId'], ['plantillasRespuesta.id'], ),
    sa.ForeignKeyConstraint(['responsableId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reclamoId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('esInternoTecnico', sa.Boolean(), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reclamoId'], ['reclamos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historialReclamos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reclamoId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reclamoId'], ['reclamos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historialReclamos')
    op.drop_table('comentarios')
    op.drop_table('reclamos')
    op.drop_table('plantillasRespuesta')
    op.drop_table('articulos_relacionados')
    op.drop_table('articulosConocimiento')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
